### PR TITLE
feature/user

### PR DESCRIPTION
**Pull request by DYung26**
implemented `GET` `/user/profile`, `GET` `/user/leaderboard`, `POST` `/user/create` and `PUT` `'/user/points'`

_don't delete this branch yet!_

### CODE REVIEW

**Review by AdebayoMarzouq — CHANGES_REQUESTED** [review]
1. getUserTasksHistory should be a combination of UserCompletedTasks and Tasks models. Your current implementation tries to fetch task with id of user id (won't work)
2. getUserOrderedByPoints should sort based on claimed + unclaimed tokens. rewaredTokens is an object. Does it auth add its properties and sorts them?

**Review by AdebayoMarzouq — CHANGES_REQUESTED** [review]
@DYung26 
1. updateuserPoints in UserController is updating tokens not reward. Please look into it. Is there any reason for this?

**Review by AdebayoMarzouq — CHANGES_REQUESTED** [review]
@DYung26 
1. let's make the put request path 'user/points'. We don't need to pass the id, it is not necessary, it is not utilized by any functions or methods and authentication already adds the user Id to session

**Comment by DYung26** [comment]
> @DYung26
> 
> 1. let's make the put request path 'user/points'. We don't need to pass the id, it is not necessary, it is not utilized by any functions or methods and authentication already adds the user Id to session

yeah, already corrected this in the latest commit

**Comment by AdebayoMarzouq** [comment]
> > @DYung26
> > 
> > 1. let's make the put request path 'user/points'. We don't need to pass the id, it is not necessary, it is not utilized by any functions or methods and authentication already adds the user Id to session
> 
> yeah, already corrected this in the latest commit

yeah I saw that at the end

**Comment by AdebayoMarzouq** [comment]
> > @DYung26
> > 
> > 1. let's make the put request path 'user/points'. We don't need to pass the id, it is not necessary, it is not utilized by any functions or methods and authentication already adds the user Id to session
> 
> yeah, already corrected this in the latest commit

@DYung26 Also let's work on that join in mongodb. It will solve some of the problems we have. We still need to be able to fetch tasks (completed and not completed as long as they are not past deadline). This way, the user can know the tasks that they have completed and the ones they have not

**Comment by DYung26** [comment]
> 1. getUserTasksHistory should be a combination of UserCompletedTasks and Tasks models. Your current implementation tries to fetch task with id of user id (won't work)
> 2. getUserOrderedByPoints should sort based on claimed + unclaimed tokens. rewaredTokens is an object. Does it auth add its properties and sorts them?

- `getUserOrderedByPoints`: corrected, a new optional field `totalTokens` was added to `User` to simplify the implementaion
- `getUserTasksHistory`: _I have not implemented anything for this yet, I guess I just wrote a sample code; that's why I didn't mark the `/user/tasks/history` endpoint as done yet!_

**Comment by DYung26** [comment]
> @DYung26
> 
> 1. updateuserPoints in UserController is updating tokens not reward. Please look into it. Is there any reason for this?

oh, the naming?, using `tokens` key to retrieve rewards, I'll use rewardTokens instead, but we might need schemas to ensure that the data is sent in the expected format from frontend, or just clearly state it in the docs.

**Comment by DYung26** [comment]
> > > @DYung26
> > > 
> > > 1. let's make the put request path 'user/points'. We don't need to pass the id, it is not necessary, it is not utilized by any functions or methods and authentication already adds the user Id to session
> > 
> > 
> > yeah, already corrected this in the latest commit
> 
> @DYung26 Also let's work on that join in mongodb. It will solve some of the problems we have. We still need to be able to fetch tasks (completed and not completed as long as they are not past deadline). This way, the user can know the tasks that they have completed and the ones they have not

OK, on it,...
so to get incomplete tasks, we retrieve all tasks from the `Task` collection and then filter out the tasks that are found in the `UserTask` collection for a given user, since `UserTask` contains only completed tasks.

But, we know it will be easier if `UserTask` just have a status field that identifies `completed` or `pending` tasks, don't know your reason for `UserTask` being `UserCompletedTask`, but I guess you have...

**Comment by AdebayoMarzouq** [comment]
> > > > @DYung26
> > > > 
> > > > 1. let's make the put request path 'user/points'. We don't need to pass the id, it is not necessary, it is not utilized by any functions or methods and authentication already adds the user Id to session
> > > 
> > > 
> > > yeah, already corrected this in the latest commit
> > 
> > 
> > @DYung26 Also let's work on that join in mongodb. It will solve some of the problems we have. We still need to be able to fetch tasks (completed and not completed as long as they are not past deadline). This way, the user can know the tasks that they have completed and the ones they have not
> 
> OK, on it,... so to get incomplete tasks, we retrieve all tasks from the `Task` collection and then filter out the tasks that are found in the `UserTask` collection for a given user, since `UserTask` contains only completed tasks.
> 
> But, we know it will be easier if `UserTask` just have a status field that identifies `completed` or `pending` tasks, don't know your reason for `UserTask` being `UserCompletedTask`, but I guess you have...

@DYung26 If you feel adding that field would make our work easier, let's add it. The result is what matters tbh.
Also yes we'll fetch all the tasks and join the UserTask collection on taskId. We don't really need to filter

**Review by AdebayoMarzouq — CHANGES_REQUESTED** [review]
UserRepoImpl correction. Makes sense but we can optimize the update for total tokens. When we can just increment total tokens with the new tokens since it is initally 0. So it never changes and we can always increment it till eternity. We'll just be making adjustments to withdrawals on the claimed and unclaimed

ex: $inc: {totalTokens: tokens}

**Comment by DYung26** [comment]
> > > > > @DYung26
> > > > > 
> > > > > 1. let's make the put request path 'user/points'. We don't need to pass the id, it is not necessary, it is not utilized by any functions or methods and authentication already adds the user Id to session
> > > > 
> > > > 
> > > > yeah, already corrected this in the latest commit
> > > 
> > > 
> > > @DYung26 Also let's work on that join in mongodb. It will solve some of the problems we have. We still need to be able to fetch tasks (completed and not completed as long as they are not past deadline). This way, the user can know the tasks that they have completed and the ones they have not
> > 
> > 
> > OK, on it,... so to get incomplete tasks, we retrieve all tasks from the `Task` collection and then filter out the tasks that are found in the `UserTask` collection for a given user, since `UserTask` contains only completed tasks.
> > But, we know it will be easier if `UserTask` just have a status field that identifies `completed` or `pending` tasks, don't know your reason for `UserTask` being `UserCompletedTask`, but I guess you have...
> 
> @DYung26 If you feel adding that field would make our work easier, let's add it. The result is what matters tbh. Also yes we'll fetch all the tasks and join the UserTask collection on taskId. We don't really need to filter

lemme check out JOIN first, then we can decide

**Comment by DYung26** [comment]
> UserRepoImpl correction. Makes sense but we can optimize the update for total tokens. When we can just increment total tokens with the new tokens since it is initally 0. So it never changes and we can always increment it till eternity. We'll just be making adjustments to withdrawals on the claimed and unclaimed
> 
> ex: $inc: {totalTokens: tokens}

yeah, thought of doing this too, but there can't be two $inc operators in one update
this can be done tho:
```
$inc: {
    'tokens.unclaimed': tokens,
    'totalTokens': tokens
}

**Pull request merged**
